apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-git
  namespace: argocd # insert your argocd namespace
spec:
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
             repoURL: https://xxxxxx.gitlab.yandexcloud.net/demo/infrastructure.git # insert your gitlab instance address
             revision: HEAD
             directories:
              - path: secure-charts/*
          # cluster generator, 'child' #2
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
    spec:
      project: demo1
      source:
        repoURL: https://xxxxxx.gitlab.yandexcloud.net/demo/infrastructure.git # insert your gitlab instance address
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true